server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/eb_water_resources?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deletedAt
      logic-delete-value: now()
      logic-not-delete-value: null

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    org.springframework.web: INFO
    com.baomidou.mybatisplus: DEBUG
    com.example.demo: DEBUG

knife4j:
  enable: true
  production: false

demo:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: mySecretKeyForEbWaterResourcesProject2025
    # 设置jwt过期时间(毫秒)
    admin-ttl: 2147483647000
    # 设置刷新令牌过期时间(毫秒)
    admin-refresh-ttl: 2147483647000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization

file:
  upload-dir: uploads/inspection
